### ISSUE TITLE
Help using this please

### ISSUE THREAD

**Issue by mathmoclaire** [sand500/SlackLateX#6]
Hi,
I would love to be able to use latex in slack but I'm not familiar with how to install things in slack, so don't understand the instructions under "how to use". Are you able to give me more specific instructions on what to do? This would be very much appreciated, thanks!

**Comment by sand500** [comment]
This uses something called node.js which lets you run javascript. Once you install nodejs, go to the directory you placed the `bot.js` file and use those commands from terminal to install the required dependencies. You need to have a slack API token either of yourself or of a bot from the [Bots slack app](https://slack.com/apps/A0F7YS25R-bots) so that this program can make posts on your slack.

**Comment by mathmoclaire** [comment]
Thanks so much, that worked!
